### PR TITLE
Exams by Max Siryk

### PR DESCRIPTION
**Pull request by erotourtes**
Hi👋, I'm Max Siryk from IM-21

### CODE REVIEW

**Comment by kol-oss** [comment]
Nothing to add.

**Review by kol-oss — APPROVED** [review]

**Comment by erotourtes** [comment]
> Nothing to add.

What do you think, if I change object `brackets` to a queue or a circular array, would it be better? 
if might look like this 
```js
const quotes = (str) => {
  const res = new Array(str.length);
  const queue = [ '«', '»' ];

  for (const char of str) {
    if (char !== '"') {
      res.push(char);
      continue;
    }

    const bracket = queue.shift();
    res.push(bracket);
    queue.push(bracket);
  }

  return res.join('');
};

```

**Comment by kol-oss** [comment]
> > Nothing to add.
> 
> What do you think, if I change object `brackets` to a queue or a circular array, would it be better? if might look like this
> 
> ```js
> const quotes = (str) => {
>   const res = new Array(str.length);
>   const queue = [ '«', '»' ];
> 
>   for (const char of str) {
>     if (char !== '"') {
>       res.push(char);
>       continue;
>     }
> 
>     const bracket = queue.shift();
>     res.push(bracket);
>     queue.push(bracket);
>   }
> 
>   return res.join('');
> };
> ```

I think that doing this way will be less efficient and readable than you haave now. This code will work perfectly but using object with keys that named like quotes is easier to understand when you read code. Also, repeated operations with array will use a lot of memory that will make your code slower.

**Comment by erotourtes** [comment]
> I think that doing this way will be less efficient and readable than you haave now. This code will work perfectly but using object with keys that named like quotes is easier to understand when you read code. Also, repeated operations with array will use a lot of memory that will make your code slower.

I see, thanks, really appreciate it

**Comment by BbIXOD** [comment]
Now I think all works perfectly)

**Review by tshemsedinov — APPROVED** [review]

**Review by tshemsedinov — APPROVED** [review]
LGTM (looks good to me)

**Pull request closed without merging**
