### PR TITLE
Exams

### PR DESCRIPTION
**Pull request by tomatorepublic**

### CODE REVIEW

**Comment by tshemsedinov** [comment]
- Improve naming
- Use eslint and prettier
- Try to use `includes` method instead of `indexOf`
- If we use block in one branch of if-statement we should use it for another branch too
- Prefer arrow functions
- Don't change incoming parameters
- Don't change `days` from function

**Comment by tomatorepublic** [comment]
> > * Try to use `includes` method instead of `indexOf`

But if this is not a high-load application, then maybe we could use regexp.
Can we use it? This way the code will be smaller and more understandable.

**Comment by tshemsedinov** [comment]
`str.substring(str.indexOf(prefix)+prefix.length, str.indexOf(suffix))` is ok but it's better to use intermediate variables:
```js
const start = str.indexOf(prefix) + prefix.length;
const end = str.indexOf(suffix);
const result = str.substring(start, end);
```

**Comment by tshemsedinov** [comment]
Avoid regexp, it can bring security and performance problems

**Pull request closed without merging**
