### PR TITLE
Exams

### PR DESCRIPTION
**Pull request by olegoofy**

### CODE REVIEW

**Review by tshemsedinov — COMMENTED** [review]
- Use eslint and prettier
- Follow style and naming conventions
- Respect 2 space indentation
- Don't change incoming parameters
- Prefer for or for..of
- Use intermediate variables, decompose long expressions

**Comment by tshemsedinov** [comment]
No surname in form (

**Comment by olegoofy** [comment]
My surname is Martynenko

**Comment by olegoofy** [comment]
I added it to form

**Pull request closed without merging**
