### PR TITLE
Exams

### PR DESCRIPTION
**Pull request by VladimirDan**

### CODE REVIEW

**Review by tshemsedinov — COMMENTED** [review]
- Use eslint and prettier
- Follow style and naming conventions
- Respect 2 space indentation
- Don't change incoming parameters
- Prefer const
- Prefer for and for..of
- Use round brackets even for single argument lambda functions
- Use intermediate variables, decompose long expressions

**Comment by tshemsedinov** [comment]
No surname in form (

**Comment by VladimirDan** [comment]
> 

Даніленко Володимир

**Comment by VladimirDan** [comment]
Даніленко

ср, 5 січ. 2022 р. о 17:04 Timur Shemsedinov ***@***.***>
пише:

**Pull request closed without merging**
